FROM node:20-bookworm-slim AS base

# Disable npm update notifications and configure Node.js defaults
ENV npm_config_update_notifier=false \
    NODE_ENV=production \
    CI=true \
    PORT=3000

WORKDIR /app

FROM base AS deps

# Enable installing dev dependencies for the build
ENV NODE_ENV=development

COPY package.json package-lock.json ./

RUN npm ci

FROM deps AS build

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG RESEND_GENERAL_AUDIENCE_ID
ARG COLLABORATION_NOTIFICATION_EMAIL
ARG NEXT_PUBLIC_APP_URL
ARG LANDING_MODE

ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
    SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY} \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY} \
    STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} \
    STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET} \
    RESEND_API_KEY=${RESEND_API_KEY} \
    RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL} \
    RESEND_GENERAL_AUDIENCE_ID=${RESEND_GENERAL_AUDIENCE_ID} \
    COLLABORATION_NOTIFICATION_EMAIL=${COLLABORATION_NOTIFICATION_EMAIL} \
    NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL} \
    LANDING_MODE=${LANDING_MODE} \
    NEXT_PUBLIC_LANDING_MODE=${LANDING_MODE}

ENV NODE_ENV=production

COPY . .

RUN npm run build

FROM base AS runtime

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG RESEND_GENERAL_AUDIENCE_ID
ARG COLLABORATION_NOTIFICATION_EMAIL
ARG NEXT_PUBLIC_APP_URL
ARG LANDING_MODE

ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY} \
    SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY} \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY} \
    STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} \
    STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET} \
    RESEND_API_KEY=${RESEND_API_KEY} \
    RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL} \
    RESEND_GENERAL_AUDIENCE_ID=${RESEND_GENERAL_AUDIENCE_ID} \
    COLLABORATION_NOTIFICATION_EMAIL=${COLLABORATION_NOTIFICATION_EMAIL} \
    NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL} \
    LANDING_MODE=${LANDING_MODE}

# Copy only the files needed for production
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/package-lock.json ./package-lock.json

RUN npm ci --omit=dev

COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next

EXPOSE 3000

CMD ["npm", "run", "start"]
