import type { OperatorModuleKey } from "@/lib/operator/console-snapshot";

export const operatorRecordCrudTypes = [
  "organization",
  "contact",
  "alert",
  "buyer_opportunity",
  "supplier_opportunity",
  "supplier_asset",
  "contract",
  "license_clause",
  "consent_record",
  "dataset_brief",
  "delivery",
  "subscription",
  "delta_manifest",
  "build",
  "build_plan",
  "dataset",
  "dataset_version",
  "modality_contract",
  "qa_report",
  "cleanlab_qa_pass",
  "enrichment_manifest",
  "label_batch",
  "active_learning_loop",
  "dsar_request",
  "pii_map",
  "catalogue_listing",
  "private_offer",
  "sample_preview_access",
  "quote",
  "invoice",
  "payout",
  "run",
  "cost_entry",
  "escalation_case",
  "audit_event",
  "integration",
  "signing_key",
] as const;

export type OperatorRecordCrudType = (typeof operatorRecordCrudTypes)[number];

export type OperatorRecordCrudDescriptor = {
  label: string;
  defaultState: string;
  stateOptions: string[];
  canCreate: boolean;
  canUpdate: boolean;
  canDelete: boolean;
  immutableReason?: string;
};

export type OperatorRecordFormGuidance = {
  primaryLabel: string;
  primaryPlaceholder: string;
  detailLabel: string;
  detailPlaceholder: string;
  detailHelp: string;
  createHelp?: string;
};

export type OperatorRecordFieldDescriptor = {
  key: string;
  label: string;
  placeholder: string;
  help: string;
  kind: "integer" | "decimal" | "text";
  min?: number;
  max?: number;
  step?: string;
  maxLength?: number;
  allowedValues?: readonly string[];
  caseTransform?: "upper" | "lower";
};

export const operatorModuleCreateTargets = {
  pipeline: "alert",
  leads: "buyer_opportunity",
  suppliers: "organization",
  buyers: "organization",
  builds: "build",
  datasets: "dataset",
  labeling: "label_batch",
  quality: "qa_report",
  privacy: "license_clause",
  catalogue: "catalogue_listing",
  commercials: "quote",
  operations: "run",
  escalations: "escalation_case",
  audit: "audit_event",
  settings: "integration",
} as const satisfies Record<OperatorModuleKey, OperatorRecordCrudType>;

export const operatorModuleCreateOptions = {
  pipeline: ["alert"],
  leads: ["buyer_opportunity", "supplier_opportunity"],
  suppliers: ["organization", "contact", "contract", "supplier_asset"],
  buyers: ["organization", "contact", "dataset_brief", "subscription", "delivery"],
  builds: ["build", "build_plan", "run"],
  datasets: ["dataset", "dataset_version", "delta_manifest", "modality_contract", "pii_map"],
  labeling: ["label_batch", "active_learning_loop"],
  quality: ["qa_report", "cleanlab_qa_pass", "enrichment_manifest"],
  privacy: ["license_clause", "consent_record", "dsar_request", "pii_map"],
  catalogue: ["catalogue_listing", "private_offer", "sample_preview_access"],
  commercials: ["quote", "contract", "invoice", "payout"],
  operations: ["run", "alert", "cost_entry"],
  escalations: ["escalation_case", "alert"],
  audit: ["audit_event"],
  settings: ["integration"],
} as const satisfies Record<OperatorModuleKey, readonly OperatorRecordCrudType[]>;

export const operatorRecordCrudDescriptors: Record<
  OperatorRecordCrudType,
  OperatorRecordCrudDescriptor
> = {
  organization: {
    label: "Organization",
    defaultState: "active",
    stateOptions: ["active", "paused", "archived"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  contact: {
    label: "Contact",
    defaultState: "contact",
    stateOptions: ["contact", "signing_authority"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  alert: {
    label: "Alert",
    defaultState: "open",
    stateOptions: ["open", "acknowledged", "resolved"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  buyer_opportunity: {
    label: "Buyer opportunity",
    defaultState: "new",
    stateOptions: [
      "new",
      "qualifying",
      "scoping",
      "feasibility",
      "pilot_quoted",
      "pilot_active",
      "pilot_delivered",
      "full_quoted",
      "full_active",
      "delivered",
      "on_subscription",
      "closed_won",
      "closed_lost",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  supplier_opportunity: {
    label: "Supplier opportunity",
    defaultState: "new",
    stateOptions: [
      "new",
      "qualifying",
      "nda_signed",
      "sample_received",
      "feasibility_done",
      "pilot_active",
      "pilot_done",
      "full_active",
      "live",
      "paused",
      "terminated",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  supplier_asset: {
    label: "Supplier asset",
    defaultState: "declared",
    stateOptions: [
      "declared",
      "sample_received",
      "rights_review",
      "approved",
      "blocked",
      "retired",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  contract: {
    label: "Contract",
    defaultState: "drafting",
    stateOptions: [
      "drafting",
      "awaiting_buyer",
      "awaiting_supplier",
      "signed",
      "active",
      "renewed",
      "terminated",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  license_clause: {
    label: "License clause",
    defaultState: "draft",
    stateOptions: ["draft", "active", "expired", "superseded"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  consent_record: {
    label: "Consent record",
    defaultState: "active",
    stateOptions: ["active", "withdrawn", "expired"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  dataset_brief: {
    label: "Dataset brief",
    defaultState: "new",
    stateOptions: ["new", "scoped", "quoted", "active", "delivered", "closed"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  delivery: {
    label: "Delivery",
    defaultState: "scheduled",
    stateOptions: [
      "scheduled",
      "preparing",
      "ready",
      "sent",
      "downloaded",
      "accepted",
      "disputed",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  subscription: {
    label: "Subscription",
    defaultState: "draft",
    stateOptions: ["draft", "active", "refreshing", "paused", "terminated", "blocked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  delta_manifest: {
    label: "Delta manifest",
    defaultState: "draft",
    stateOptions: ["draft", "validating", "ready", "published", "tombstoned", "blocked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  build: {
    label: "Build",
    defaultState: "planned",
    stateOptions: [
      "planned",
      "intaking",
      "profiling",
      "cleaning",
      "privacy",
      "enriching",
      "labeling",
      "qa",
      "packaging",
      "released",
      "delivered",
      "rework",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  build_plan: {
    label: "Build plan",
    defaultState: "draft",
    stateOptions: ["draft", "approved", "superseded"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  dataset: {
    label: "Dataset",
    defaultState: "draft",
    stateOptions: ["draft", "active", "retired"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  dataset_version: {
    label: "Dataset version",
    defaultState: "draft",
    stateOptions: ["draft", "released", "deprecated"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  modality_contract: {
    label: "Modality contract",
    defaultState: "draft",
    stateOptions: ["draft", "review", "approved", "blocked", "superseded"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  qa_report: {
    label: "QA report",
    defaultState: "review",
    stateOptions: ["pass", "review", "fail"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  cleanlab_qa_pass: {
    label: "Cleanlab QA pass",
    defaultState: "draft",
    stateOptions: ["draft", "scanning", "review", "requeue", "accepted", "blocked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  enrichment_manifest: {
    label: "Enrichment manifest",
    defaultState: "draft",
    stateOptions: ["draft", "review", "approved", "blocked", "superseded"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  label_batch: {
    label: "Label batch",
    defaultState: "queued",
    stateOptions: ["queued", "in_review", "in_adjudication", "closed", "requeued"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  active_learning_loop: {
    label: "Active-learning loop",
    defaultState: "draft",
    stateOptions: ["draft", "sampling", "review", "queued", "closed", "blocked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  dsar_request: {
    label: "DSAR request",
    defaultState: "received",
    stateOptions: [
      "received",
      "identity_verified",
      "impact_assessed",
      "propagating",
      "completed",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  pii_map: {
    label: "PII map",
    defaultState: "review",
    stateOptions: ["review", "approved", "blocked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  catalogue_listing: {
    label: "Catalogue listing",
    defaultState: "draft",
    stateOptions: ["draft", "review", "active", "paused", "retired"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  private_offer: {
    label: "Private offer",
    defaultState: "draft",
    stateOptions: ["draft", "sent", "accepted", "expired", "withdrawn"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  sample_preview_access: {
    label: "Sample preview access",
    defaultState: "requested",
    stateOptions: [
      "requested",
      "nda_acknowledged",
      "approved",
      "denied",
      "revoked",
      "expired",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  quote: {
    label: "Quote",
    defaultState: "draft",
    stateOptions: ["draft", "sent", "accepted", "rejected", "expired"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  invoice: {
    label: "Invoice",
    defaultState: "draft",
    stateOptions: ["draft", "open", "paid", "void", "uncollectible"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  payout: {
    label: "Payout",
    defaultState: "pending",
    stateOptions: ["pending", "paid", "failed", "held"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  run: {
    label: "Run",
    defaultState: "queued",
    stateOptions: ["queued", "running", "succeeded", "failed", "cancelled"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  cost_entry: {
    label: "Cost entry",
    defaultState: "USD",
    stateOptions: ["USD", "EUR", "GBP"],
    canCreate: true,
    canUpdate: false,
    canDelete: false,
    immutableReason: "Cost entries are ledger records and remain append-only.",
  },
  escalation_case: {
    label: "Escalation case",
    defaultState: "open",
    stateOptions: [
      "open",
      "triaged",
      "mitigating",
      "monitoring",
      "resolved",
      "cancelled",
    ],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  audit_event: {
    label: "Audit event",
    defaultState: "operator_manual_marker",
    stateOptions: ["operator_manual_marker"],
    canCreate: true,
    canUpdate: false,
    canDelete: false,
    immutableReason: "Audit events are append-only and cannot be edited or deleted.",
  },
  integration: {
    label: "Integration",
    defaultState: "paused",
    stateOptions: ["active", "paused", "revoked"],
    canCreate: true,
    canUpdate: true,
    canDelete: true,
  },
  signing_key: {
    label: "Signing key",
    defaultState: "active",
    stateOptions: ["active", "retired", "revoked"],
    canCreate: false,
    canUpdate: true,
    canDelete: true,
  },
};

export const operatorRecordFormGuidance = {
  organization: {
    primaryLabel: "Legal or display name",
    primaryPlaceholder: "Acme Mobility Data",
    detailLabel: "Website",
    detailPlaceholder: "https://example.com",
    detailHelp: "Stored as the organization website when provided.",
    createHelp: "The selected module determines whether this starts as a buyer, supplier, or partner organization.",
  },
  contact: {
    primaryLabel: "Full name",
    primaryPlaceholder: "Marta Alvarez",
    detailLabel: "Role or signing authority note",
    detailPlaceholder: "General Counsel",
    detailHelp: "Stored as the contact role; the signing-authority state also marks the contact as authorized to sign.",
  },
  alert: {
    primaryLabel: "Alert title",
    primaryPlaceholder: "G-4 privacy gate blocked",
    detailLabel: "Escalation note",
    detailPlaceholder: "PII map needs legal review before packaging.",
    detailHelp: "Stored in the audit payload and visible as operator context.",
  },
  buyer_opportunity: {
    primaryLabel: "Opportunity title",
    primaryPlaceholder: "Fraud model evaluation dataset",
    detailLabel: "Use case",
    detailPlaceholder: "Buyer needs EU transaction samples for model evaluation.",
    detailHelp: "Stored as the buyer use case; opportunity metadata fields are captured below.",
  },
  supplier_opportunity: {
    primaryLabel: "Opportunity title",
    primaryPlaceholder: "Regional logistics telemetry supply",
    detailLabel: "Asset summary",
    detailPlaceholder: "GPS traces, delivery events, and route exceptions.",
    detailHelp: "Stored as the supplier asset summary.",
  },
  supplier_asset: {
    primaryLabel: "Asset name",
    primaryPlaceholder: "Retail receipts 2025 sample",
    detailLabel: "Rights summary",
    detailPlaceholder: "Owned POS data, no third-party enrichment.",
    detailHelp: "Stored in the rights-summary JSON as an operator note; asset metadata fields are captured below.",
  },
  contract: {
    primaryLabel: "Contract reference",
    primaryPlaceholder: "MSA with Acme Mobility",
    detailLabel: "Document URI",
    detailPlaceholder: "s3://contracts/acme-msa.pdf",
    detailHelp: "Stored as the contract document URI; structured term fields are captured below.",
    createHelp: "Creation links to the most recently updated organization in this operator org.",
  },
  license_clause: {
    primaryLabel: "Clause label",
    primaryPlaceholder: "EU training and evaluation permit",
    detailLabel: "Clause note",
    detailPlaceholder: "Training and evaluation allowed; redistribution blocked.",
    detailHelp: "Stored as license notes and asset-scope summary; permitted-use fields are captured below.",
    createHelp: "Requires at least one existing contract in this operator org.",
  },
  consent_record: {
    primaryLabel: "Subject reference",
    primaryPlaceholder: "subject_hash_74c...",
    detailLabel: "Lawful basis or evidence URI",
    detailPlaceholder: "contract",
    detailHelp: "Stored as lawful basis on create; explicit privacy evidence fields are captured below.",
    createHelp: "Requires at least one supplier asset in this operator org.",
  },
  dataset_brief: {
    primaryLabel: "Brief title",
    primaryPlaceholder: "Iberian retail receipt benchmark",
    detailLabel: "Requirements summary",
    detailPlaceholder: "Receipt OCR, category labels, and monthly refresh.",
    detailHelp: "Stored in the brief requirements JSON; delivery and sensitivity fields are captured below.",
  },
  delivery: {
    primaryLabel: "Delivery channel",
    primaryPlaceholder: "S3 cross-account share",
    detailLabel: "Receipt or acceptance note",
    detailPlaceholder: "Buyer notified; awaiting acceptance.",
    detailHelp: "Stored in the delivery receipt JSON; channel and receipt fields are captured below.",
    createHelp: "Requires at least one dataset version; buyer defaults to the latest buyer organization when available.",
  },
  subscription: {
    primaryLabel: "Subscription label",
    primaryPlaceholder: "Retail receipts monthly feed",
    detailLabel: "Delivery policy note",
    detailPlaceholder: "Latest plus three rolling refreshes through Delta Share.",
    detailHelp: "Stored in the subscription delivery policy; cadence and window fields are captured below.",
    createHelp: "Requires at least one dataset and links to the latest buyer organization when available.",
  },
  build: {
    primaryLabel: "Build title",
    primaryPlaceholder: "Retail receipts v4 packaging",
    detailLabel: "Build note",
    detailPlaceholder: "Rework duplicate clusters before G-7.",
    detailHelp: "Stored in the audit payload; ETA, score, and cost fields are captured below.",
  },
  build_plan: {
    primaryLabel: "Plan label",
    primaryPlaceholder: "Plan for retail receipts v4",
    detailLabel: "Manifest YAML",
    detailPlaceholder: "version: operator-created",
    detailHelp: "Stored as the build-plan manifest YAML; license-gate fields are captured below.",
    createHelp: "Requires at least one build in this operator org.",
  },
  dataset: {
    primaryLabel: "Dataset name",
    primaryPlaceholder: "Iberian retail receipts",
    detailLabel: "Modality",
    detailPlaceholder: "tabular",
    detailHelp: "Stored as the dataset modality; the explicit field below is preferred when provided.",
  },
  dataset_version: {
    primaryLabel: "Version label",
    primaryPlaceholder: "v2026.05",
    detailLabel: "Manifest URI",
    detailPlaceholder: "s3://datasets/receipts/v2026.05/manifest.json",
    detailHelp: "Stored as the manifest URI; version metrics are captured below.",
    createHelp: "Requires at least one dataset in this operator org.",
  },
  delta_manifest: {
    primaryLabel: "Delta label",
    primaryPlaceholder: "Retail receipts 2026-05 refresh delta",
    detailLabel: "Delta summary",
    detailPlaceholder: "1,250 new records, 48 corrections, 4 deletions.",
    detailHelp: "Stored as delta-manifest summary; QA, privacy, rights, and change-count evidence fields are captured below.",
    createHelp: "Requires at least one subscription, dataset version, delivery, and QA report in this operator org.",
  },
  modality_contract: {
    primaryLabel: "Contract label",
    primaryPlaceholder: "Document extraction contract",
    detailLabel: "Canonical format",
    detailPlaceholder: "Parquet page records plus original PDF references",
    detailHelp: "Stored as the modality contract canonical format; contract fields are captured below.",
    createHelp: "Requires at least one dataset version in this operator org.",
  },
  qa_report: {
    primaryLabel: "Report label",
    primaryPlaceholder: "G-7 QA scorecard",
    detailLabel: "Dimension summary",
    detailPlaceholder: "Completeness 0.99, accuracy 0.91, privacy 1.00.",
    detailHelp: "Stored in the QA dimensions JSON.",
  },
  cleanlab_qa_pass: {
    primaryLabel: "Pass label",
    primaryPlaceholder: "Receipt OCR Cleanlab scan",
    detailLabel: "Scan summary",
    detailPlaceholder: "Confident-learning scan found 3 likely label errors for reviewer requeue.",
    detailHelp: "Stored as the Cleanlab summary; scan evidence fields are captured below.",
    createHelp: "Requires a QA report and links to the latest label batch when available.",
  },
  enrichment_manifest: {
    primaryLabel: "Manifest label",
    primaryPlaceholder: "G-5 geospatial enrichment",
    detailLabel: "Computation method",
    detailPlaceholder: "H3 binning from silver coordinates with OSM boundary join.",
    detailHelp: "Stored as the reproducible enrichment method; source and license fields are captured below.",
    createHelp: "Requires at least one build or dataset version in this operator org.",
  },
  label_batch: {
    primaryLabel: "Batch label",
    primaryPlaceholder: "Batch for receipt line items",
    detailLabel: "Batch note",
    detailPlaceholder: "Escalate low agreement categories.",
    detailHelp: "Stored in the audit payload; operational queue metrics are captured in the fields below.",
    createHelp: "Requires at least one build in this operator org.",
  },
  active_learning_loop: {
    primaryLabel: "Loop label",
    primaryPlaceholder: "Crop imagery active-learning loop",
    detailLabel: "Selection summary",
    detailPlaceholder: "High-uncertainty and diverse boundary samples selected for reviewer pass.",
    detailHelp: "Stored as active-learning selection summary; FiftyOne/Lightly routing evidence is captured below.",
    createHelp: "Requires at least one build and links to the latest label batch when available.",
  },
  dsar_request: {
    primaryLabel: "Subject reference",
    primaryPlaceholder: "subject_hash_74c...",
    detailLabel: "Request note",
    detailPlaceholder: "Access request received through privacy inbox.",
    detailHelp: "Stored in the audit payload; request type and SLA fields are captured below.",
  },
  pii_map: {
    primaryLabel: "PII map label",
    primaryPlaceholder: "Receipt PII review",
    detailLabel: "Findings summary",
    detailPlaceholder: "Names masked; loyalty IDs hashed.",
    detailHelp: "Stored in the PII findings JSON; treatment summary is captured below.",
    createHelp: "Requires at least one dataset version in this operator org.",
  },
  catalogue_listing: {
    primaryLabel: "Listing title",
    primaryPlaceholder: "Retail receipt OCR dataset",
    detailLabel: "Pricing or listing note",
    detailPlaceholder: "Private offer only until supplier approval.",
    detailHelp: "Stored in the listing pricing JSON; structured commercial fields are captured below.",
    createHelp: "Requires at least one dataset in this operator org.",
  },
  private_offer: {
    primaryLabel: "Offer label",
    primaryPlaceholder: "Acme evaluation pilot offer",
    detailLabel: "Commercial terms",
    detailPlaceholder: "30-day evaluation, no redistribution.",
    detailHelp: "Stored in the private-offer terms JSON; structured offer fields are captured below.",
    createHelp: "Requires at least one dataset and links to the latest buyer organization when available.",
  },
  sample_preview_access: {
    primaryLabel: "Preview access label",
    primaryPlaceholder: "Acme NDA-gated receipt preview",
    detailLabel: "Decision reason",
    detailPlaceholder: "Buyer acknowledged NDA; grant 14-day watermarked access.",
    detailHelp: "Stored as the preview-access decision reason; gating fields are captured below.",
    createHelp: "Requires at least one catalogue listing and links to the latest buyer organization when available.",
  },
  quote: {
    primaryLabel: "Quote label",
    primaryPlaceholder: "Pilot quote for Acme",
    detailLabel: "Quote note",
    detailPlaceholder: "Pricing handled by finance before send.",
    detailHelp: "Stored in the audit payload; commercial amount fields are captured below.",
  },
  invoice: {
    primaryLabel: "Invoice label",
    primaryPlaceholder: "Pilot invoice",
    detailLabel: "Stripe invoice ID",
    detailPlaceholder: "in_...",
    detailHelp: "Stored as the Stripe invoice ID.",
    createHelp: "Requires at least one quote in this operator org.",
  },
  payout: {
    primaryLabel: "Payout label",
    primaryPlaceholder: "Supplier revenue share",
    detailLabel: "Stripe transfer ID",
    detailPlaceholder: "tr_...",
    detailHelp: "Stored as the Stripe transfer ID.",
    createHelp: "Links to the latest supplier organization when available.",
  },
  run: {
    primaryLabel: "External run ID",
    primaryPlaceholder: "airflow/run/receipts-v4",
    detailLabel: "Run note",
    detailPlaceholder: "Retry after worker capacity recovers.",
    detailHelp: "Primary field stores or updates the external run ID; retry/timing fields are captured below.",
    createHelp: "Requires at least one build in this operator org.",
  },
  cost_entry: {
    primaryLabel: "Cost category",
    primaryPlaceholder: "labeling_review",
    detailLabel: "Cost metadata",
    detailPlaceholder: "Reviewer batch cost estimate.",
    detailHelp: "Stored as immutable cost metadata; amount fields are captured below and entries are append-only.",
  },
  escalation_case: {
    primaryLabel: "Escalation title",
    primaryPlaceholder: "Supplier delivery failure - retail receipts sample",
    detailLabel: "Escalation detail",
    detailPlaceholder: "Supplier sample delivery is late and the buyer pilot date is at risk.",
    detailHelp: "Stored as the escalation detail; runbook routing fields are captured below.",
    createHelp:
      "Creation automatically routes the case to the mapped runbook, opens an alert, and records an audit event.",
  },
  audit_event: {
    primaryLabel: "Audit action",
    primaryPlaceholder: "operator_manual_marker",
    detailLabel: "Audit note",
    detailPlaceholder: "Manual checkpoint recorded before release.",
    detailHelp: "Stored in audit metadata; audit events are append-only.",
  },
  integration: {
    primaryLabel: "Provider",
    primaryPlaceholder: "snowflake",
    detailLabel: "Configuration note",
    detailPlaceholder: "Credential material is managed outside this generic form.",
    detailHelp: "Provider is editable; encrypted config remains specialized and safe by default.",
  },
  signing_key: {
    primaryLabel: "Signing key label",
    primaryPlaceholder: "delivery-signing-prod",
    detailLabel: "Rotation note",
    detailPlaceholder: "Use the dedicated signing-key card for new key generation.",
    detailHelp: "Generic edits only adjust state; creation is handled by the signing-key workflow.",
    createHelp: "Use the dedicated Settings signing-key workflow for key generation.",
  },
} as const satisfies Record<OperatorRecordCrudType, OperatorRecordFormGuidance>;

export const operatorRecordFieldDescriptors = {
  buyer_opportunity: [
    {
      key: "modality",
      label: "Modality",
      placeholder: "mixed",
      help: "Expected dataset modality for scoping and matching.",
      kind: "text",
      maxLength: 20,
      allowedValues: [
        "mixed",
        "tabular",
        "text",
        "image",
        "video",
        "audio",
        "geospatial",
        "timeseries",
        "document",
      ],
      caseTransform: "lower",
    },
    {
      key: "budgetRange",
      label: "Budget range",
      placeholder: "EUR 25k-50k",
      help: "Stored as buyer budget-range summary.",
      kind: "text",
      maxLength: 120,
    },
    {
      key: "timeline",
      label: "Timeline",
      placeholder: "Pilot in 30 days",
      help: "Buyer delivery timeline or urgency note.",
      kind: "text",
      maxLength: 120,
    },
  ],
  supplier_asset: [
    {
      key: "modality",
      label: "Modality",
      placeholder: "tabular",
      help: "Dataset modality declared by the supplier.",
      kind: "text",
      maxLength: 20,
      allowedValues: [
        "tabular",
        "text",
        "image",
        "video",
        "audio",
        "geospatial",
        "timeseries",
        "document",
      ],
      caseTransform: "lower",
    },
    {
      key: "declaredVolume",
      label: "Declared volume",
      placeholder: "12M rows, monthly refresh",
      help: "Stored as declared-volume JSON summary.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "refreshPolicy",
      label: "Refresh policy",
      placeholder: "one_shot",
      help: "How often the supplier can refresh this asset.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["one_shot", "scheduled", "on_event", "perpetual"],
      caseTransform: "lower",
    },
    {
      key: "sensitivity",
      label: "Sensitivity",
      placeholder: "confidential",
      help: "Data sensitivity class for rights and privacy review.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["public", "confidential", "pii", "special"],
      caseTransform: "lower",
    },
  ],
  contract: [
    {
      key: "contractType",
      label: "Contract type",
      placeholder: "supplier",
      help: "Legal/commercial contract type.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["supplier", "buyer", "nda", "dpa", "msa"],
      caseTransform: "lower",
    },
    {
      key: "documentUri",
      label: "Document URI",
      placeholder: "s3://contracts/acme-msa.pdf",
      help: "Canonical contract evidence URI.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "signedAt",
      label: "Signed at",
      placeholder: "2026-05-31",
      help: "Optional signed timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "startsAt",
      label: "Starts at",
      placeholder: "2026-06-01",
      help: "Optional contract start timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "endsAt",
      label: "Ends at",
      placeholder: "2027-06-01",
      help: "Optional contract end timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
  ],
  license_clause: [
    {
      key: "permittedUses",
      label: "Permitted uses",
      placeholder: "train, eval, commercial_inference",
      help: "Comma-separated uses: train, finetune, eval, commercial_inference, redistribute.",
      kind: "text",
      maxLength: 160,
      caseTransform: "lower",
    },
    {
      key: "geo",
      label: "Geography",
      placeholder: "WW, EU",
      help: "Comma-separated permitted territories.",
      kind: "text",
      maxLength: 120,
      caseTransform: "upper",
    },
    {
      key: "exclusivity",
      label: "Exclusivity",
      placeholder: "none",
      help: "Exclusive or category-exclusive rights posture.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["none", "exclusive", "category"],
      caseTransform: "lower",
    },
    {
      key: "termEndsAt",
      label: "Term ends at",
      placeholder: "2027-06-01",
      help: "Optional license end timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "shareAlike",
      label: "Share alike",
      placeholder: "false",
      help: "Whether derivative datasets inherit share-alike restrictions.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
  ],
  delivery: [
    {
      key: "channel",
      label: "Delivery channel",
      placeholder: "s3_share",
      help: "Delivery transport agreed with the buyer.",
      kind: "text",
      maxLength: 30,
      allowedValues: [
        "signed_s3",
        "signed_url",
        "s3_share",
        "warehouse_share",
        "api",
        "delta_share",
      ],
      caseTransform: "lower",
    },
    {
      key: "receiptHash",
      label: "Receipt hash",
      placeholder: "sha256:...",
      help: "Optional hash for delivery receipt or acceptance evidence.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "acceptanceWindowDays",
      label: "Acceptance window days",
      placeholder: "7",
      help: "Buyer acceptance window stored in receipt metadata.",
      kind: "integer",
      min: 1,
      max: 90,
    },
  ],
  subscription: [
    {
      key: "cadence",
      label: "Refresh cadence",
      placeholder: "monthly",
      help: "Recurring refresh cadence committed to the buyer.",
      kind: "text",
      maxLength: 30,
      allowedValues: ["weekly", "monthly", "quarterly", "event_driven", "custom"],
      caseTransform: "lower",
    },
    {
      key: "deliveryChannel",
      label: "Delivery channel",
      placeholder: "delta_share",
      help: "Transport used for recurring increments.",
      kind: "text",
      maxLength: 30,
      allowedValues: [
        "signed_s3",
        "signed_url",
        "s3_share",
        "warehouse_share",
        "api",
        "delta_share",
      ],
      caseTransform: "lower",
    },
    {
      key: "rollingWindowVersions",
      label: "Rolling window versions",
      placeholder: "3",
      help: "Number of refresh versions retained for buyer consumption.",
      kind: "integer",
      min: 1,
      max: 36,
    },
    {
      key: "nextRefreshAt",
      label: "Next refresh at",
      placeholder: "2026-06-01T09:00:00Z",
      help: "Scheduled next refresh timestamp.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "retentionDays",
      label: "Retention days",
      placeholder: "365",
      help: "Retention window stored in subscription policy.",
      kind: "integer",
      min: 1,
      max: 3650,
    },
  ],
  build: [
    {
      key: "etaAt",
      label: "ETA",
      placeholder: "2026-05-31",
      help: "Optional build ETA timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "qScore",
      label: "Q-score",
      placeholder: "0.91",
      help: "Optional build quality score from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
    {
      key: "costBudgetCents",
      label: "Budget in cents",
      placeholder: "250000",
      help: "Approved build budget in minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "llmBudgetCents",
      label: "LLM budget in cents",
      placeholder: "25000",
      help: "Dedicated LLM and embedding sub-budget in minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "externalApiBudgetCents",
      label: "External API budget in cents",
      placeholder: "15000",
      help: "Dedicated third-party API, geocoding, or enrichment sub-budget.",
      kind: "integer",
      min: 0,
    },
    {
      key: "costUsedCents",
      label: "Cost used in cents",
      placeholder: "184000",
      help: "Current build cost used in minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "costOverrideReason",
      label: "Cost override reason",
      placeholder: "Buyer approved expanded geocoding pass.",
      help: "Required when operators approve spend beyond the hard budget envelope.",
      kind: "text",
      maxLength: 240,
    },
  ],
  build_plan: [
    {
      key: "licenseBlocked",
      label: "License blocked",
      placeholder: "false",
      help: "Whether composed license terms block this plan.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
    {
      key: "permitSummary",
      label: "Permit summary",
      placeholder: "Training and evaluation allowed; redistribution blocked.",
      help: "Operator-readable composed-permit summary.",
      kind: "text",
      maxLength: 240,
    },
  ],
  qa_report: [
    {
      key: "compositeScore",
      label: "Composite score",
      placeholder: "0.94",
      help: "Optional quality score from 0 to 1; blank keeps the current score.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
  ],
  cleanlab_qa_pass: [
    {
      key: "scanStrategy",
      label: "Scan strategy",
      placeholder: "confident_learning",
      help: "Cleanlab or confident-learning strategy used for label-error detection.",
      kind: "text",
      maxLength: 40,
      allowedValues: [
        "confident_learning",
        "cleanlab_studio",
        "hybrid_confidence_agreement",
      ],
      caseTransform: "lower",
    },
    {
      key: "inputManifestUri",
      label: "Input manifest URI",
      placeholder: "s3://silver/labels/receipt-pass-1.jsonl",
      help: "Label manifest scanned for suspected label errors.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "cleanlabReportUri",
      label: "Cleanlab report URI",
      placeholder: "s3://qa/cleanlab/receipt-report.json",
      help: "Immutable Cleanlab/confident-learning report attached to QA evidence.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "modelSnapshotUri",
      label: "Model snapshot URI",
      placeholder: "s3://models/receipt-label-error-detector",
      help: "Model or embedding snapshot used to compute issue scores.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "scannedCount",
      label: "Scanned count",
      placeholder: "128",
      help: "Number of labeled items included in the Cleanlab scan.",
      kind: "integer",
      min: 1,
    },
    {
      key: "suspectedLabelErrors",
      label: "Suspected label errors",
      placeholder: "3",
      help: "Count of likely label errors found by Cleanlab.",
      kind: "integer",
      min: 0,
    },
    {
      key: "estimatedErrorRate",
      label: "Estimated error rate",
      placeholder: "0.023",
      help: "Suspected label-error rate from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.0001",
    },
    {
      key: "errorRateThreshold",
      label: "Error-rate threshold",
      placeholder: "0.03",
      help: "Maximum accepted Cleanlab error rate for this QA pass.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.0001",
    },
    {
      key: "requeueCount",
      label: "Requeue count",
      placeholder: "3",
      help: "Suspected label errors routed back to reviewers.",
      kind: "integer",
      min: 0,
    },
    {
      key: "requeueManifestUri",
      label: "Requeue manifest URI",
      placeholder: "s3://qa/cleanlab/receipt-requeue.jsonl",
      help: "Manifest of suspected errors sent back into reviewer queues.",
      kind: "text",
      maxLength: 240,
    },
  ],
  dataset_brief: [
    {
      key: "targetFormats",
      label: "Target formats",
      placeholder: "parquet, jsonl",
      help: "Comma-separated delivery formats stored on the brief.",
      kind: "text",
      maxLength: 160,
      caseTransform: "lower",
    },
    {
      key: "sensitivityConstraints",
      label: "Sensitivity constraints",
      placeholder: "No raw PII; stable pseudonyms only",
      help: "Stored as sensitivity-constraints summary JSON.",
      kind: "text",
      maxLength: 240,
    },
  ],
  dataset: [
    {
      key: "modality",
      label: "Modality",
      placeholder: "tabular",
      help: "Dataset family modality.",
      kind: "text",
      maxLength: 20,
      allowedValues: [
        "tabular",
        "text",
        "image",
        "video",
        "audio",
        "geospatial",
        "timeseries",
        "document",
      ],
      caseTransform: "lower",
    },
  ],
  dataset_version: [
    {
      key: "contentHash",
      label: "Content hash",
      placeholder: "sha256:...",
      help: "Immutable content hash for the packaged version.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "recordCount",
      label: "Record count",
      placeholder: "1250000",
      help: "Optional record count for catalogue and delivery review.",
      kind: "integer",
      min: 0,
    },
    {
      key: "sizeBytes",
      label: "Size in bytes",
      placeholder: "536870912",
      help: "Optional packaged size in bytes.",
      kind: "integer",
      min: 0,
    },
    {
      key: "qaScore",
      label: "QA score",
      placeholder: "0.94",
      help: "Optional QA score from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
  ],
  delta_manifest: [
    {
      key: "manifestUri",
      label: "Delta manifest URI",
      placeholder: "s3://datasets/receipts/v2026.05/delta.json",
      help: "Immutable manifest for this subscription increment.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "manifestHash",
      label: "Delta manifest hash",
      placeholder: "sha256:...",
      help: "Hash buyers use to verify the delta manifest.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "previousDatasetVersionId",
      label: "Previous dataset version ID",
      placeholder: "dv_...",
      help: "Previous version this increment points back to.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "deliveryId",
      label: "Delivery ID",
      placeholder: "dl_...",
      help: "Delivery receipt associated with this refresh.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "qaReportId",
      label: "QA report ID",
      placeholder: "qr_...",
      help: "Per-increment QA scorecard attached to this delta.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "addedRecords",
      label: "Added records",
      placeholder: "1250",
      help: "New records introduced by this increment.",
      kind: "integer",
      min: 0,
    },
    {
      key: "updatedRecords",
      label: "Updated records",
      placeholder: "48",
      help: "Records corrected or updated by this increment.",
      kind: "integer",
      min: 0,
    },
    {
      key: "deletedRecords",
      label: "Deleted records",
      placeholder: "4",
      help: "Records removed by this increment.",
      kind: "integer",
      min: 0,
    },
    {
      key: "tombstonedRecords",
      label: "Tombstoned records",
      placeholder: "0",
      help: "Records tombstoned because of deletion propagation.",
      kind: "integer",
      min: 0,
    },
    {
      key: "totalRecords",
      label: "Total records",
      placeholder: "51221",
      help: "Total records in the refreshed dataset version.",
      kind: "integer",
      min: 0,
    },
    {
      key: "qualityScore",
      label: "Quality score",
      placeholder: "0.94",
      help: "Per-increment QA score from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
    {
      key: "rightsReverified",
      label: "Rights reverified",
      placeholder: "true",
      help: "Whether rights were reverified for this increment.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
    {
      key: "privacyVerified",
      label: "Privacy verified",
      placeholder: "true",
      help: "Whether privacy checks passed for this increment.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
    {
      key: "deletionNoticeUri",
      label: "Deletion notice URI",
      placeholder: "s3://datasets/receipts/deletion-required.json",
      help: "Actionable deletion-required notice for tombstoned refreshes.",
      kind: "text",
      maxLength: 240,
    },
  ],
  modality_contract: [
    {
      key: "modality",
      label: "Modality",
      placeholder: "document",
      help: "Modality contract to apply to the dataset version.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["video", "audio", "geospatial", "document", "timeseries"],
      caseTransform: "lower",
    },
    {
      key: "canonicalFormat",
      label: "Canonical format",
      placeholder: "Parquet page records plus original PDF references",
      help: "Canonical storage/package representation for this modality.",
      kind: "text",
      maxLength: 120,
    },
    {
      key: "profileSignals",
      label: "Profile signals",
      placeholder: "page_count, ocr_confidence, layout_type_inventory",
      help: "Comma-separated signals required during profiling.",
      kind: "text",
      maxLength: 240,
      caseTransform: "lower",
    },
    {
      key: "cleaningOperators",
      label: "Cleaning operators",
      placeholder: "ocr_normalize, page_dedup, table_extract",
      help: "Comma-separated modality-specific cleaning operators.",
      kind: "text",
      maxLength: 240,
      caseTransform: "lower",
    },
    {
      key: "privacyTreatments",
      label: "Privacy treatments",
      placeholder: "signature_redaction, printed_pii_redaction",
      help: "Comma-separated PII/provenance treatments required before release.",
      kind: "text",
      maxLength: 240,
      caseTransform: "lower",
    },
    {
      key: "labelingWidgets",
      label: "Labeling widgets",
      placeholder: "page_region, field_extraction, table_cell",
      help: "Comma-separated annotation widgets available to reviewers.",
      kind: "text",
      maxLength: 180,
      caseTransform: "lower",
    },
    {
      key: "qaDimensions",
      label: "QA dimensions",
      placeholder: "layout_fidelity, ocr_confidence, redaction_residual",
      help: "Comma-separated modality-specific QA dimensions.",
      kind: "text",
      maxLength: 240,
      caseTransform: "lower",
    },
    {
      key: "packagingTargets",
      label: "Packaging targets",
      placeholder: "page_parquet, pdf_bundle, rest_query",
      help: "Comma-separated delivery package targets.",
      kind: "text",
      maxLength: 180,
      caseTransform: "lower",
    },
  ],
  enrichment_manifest: [
    {
      key: "enrichmentClass",
      label: "Enrichment class",
      placeholder: "derived_features",
      help: "Blueprint enrichment class used for G-5 review.",
      kind: "text",
      maxLength: 32,
      allowedValues: [
        "reference_data",
        "geospatial",
        "categorical",
        "derived_features",
        "embeddings",
        "llm_derived",
        "external_join",
      ],
      caseTransform: "lower",
    },
    {
      key: "addedColumns",
      label: "Added columns",
      placeholder: "merchant_name, receipt_total",
      help: "Comma-separated columns added by enrichment.",
      kind: "text",
      maxLength: 240,
      caseTransform: "lower",
    },
    {
      key: "sources",
      label: "Sources",
      placeholder: "OSM boundaries 2026.05",
      help: "Comma-separated source names or manifests.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "sourceLicense",
      label: "Source license",
      placeholder: "ODbL-1.0",
      help: "License that governs the enrichment source.",
      kind: "text",
      maxLength: 120,
    },
    {
      key: "sourceVersion",
      label: "Source version",
      placeholder: "2026.05",
      help: "Version or snapshot identifier for the enrichment source.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "computationMethod",
      label: "Computation method",
      placeholder: "h3 v4 resolution 8 from silver coordinates",
      help: "Reproducible method used to derive the enrichment columns.",
      kind: "text",
      maxLength: 500,
    },
    {
      key: "modelIdentityHash",
      label: "Model hash",
      placeholder: "sha256:...",
      help: "Optional model identity hash for embeddings or LLM-derived enrichments.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "promptTemplateVersion",
      label: "Prompt template",
      placeholder: "prompt_geocode_v1",
      help: "Prompt template version when enrichment used an LLM.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "reproducerUri",
      label: "Reproducer URI",
      placeholder: "s3://manifests/enrichment/geospatial-h3.json",
      help: "Manifest or code artifact used to reproduce the enrichment.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "spotCheckRate",
      label: "Spot-check rate",
      placeholder: "0.10",
      help: "Human spot-check rate from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
    {
      key: "independencePassed",
      label: "Independence passed",
      placeholder: "true",
      help: "Whether the enrichment is derivable from the silver layer only.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
    {
      key: "licenseCompatible",
      label: "License compatible",
      placeholder: "true",
      help: "Whether the enrichment license is compatible with intended use.",
      kind: "text",
      maxLength: 5,
      allowedValues: ["true", "false"],
      caseTransform: "lower",
    },
  ],
  consent_record: [
    {
      key: "lawfulBasis",
      label: "Lawful basis",
      placeholder: "contract",
      help: "Structured lawful basis used for privacy review.",
      kind: "text",
      maxLength: 40,
      allowedValues: [
        "contract",
        "consent",
        "legitimate_interest",
        "legal_obligation",
      ],
      caseTransform: "lower",
    },
    {
      key: "evidenceUri",
      label: "Evidence URI",
      placeholder: "s3://privacy/evidence/subject.pdf",
      help: "URI for consent or lawful-basis evidence.",
      kind: "text",
      maxLength: 240,
    },
  ],
  dsar_request: [
    {
      key: "requestType",
      label: "Request type",
      placeholder: "access",
      help: "DSAR request type.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["access", "delete", "correct", "export", "restrict"],
      caseTransform: "lower",
    },
    {
      key: "slaDays",
      label: "SLA days",
      placeholder: "14",
      help: "Days from now until the SLA due date.",
      kind: "integer",
      min: 1,
      max: 90,
    },
  ],
  pii_map: [
    {
      key: "treatmentSummary",
      label: "Treatment summary",
      placeholder: "Hash loyalty IDs; mask names",
      help: "Stored in the PII treatments JSON.",
      kind: "text",
      maxLength: 240,
    },
  ],
  catalogue_listing: [
    {
      key: "priceCents",
      label: "Price in cents",
      placeholder: "990000",
      help: "Catalogue or listing price stored as integer minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "currency",
      label: "Currency",
      placeholder: "USD",
      help: "Supported listing currency.",
      kind: "text",
      maxLength: 3,
      allowedValues: ["USD", "EUR", "GBP"],
      caseTransform: "upper",
    },
    {
      key: "billingModel",
      label: "Billing model",
      placeholder: "one_time",
      help: "Commercial model for the listing.",
      kind: "text",
      maxLength: 30,
      allowedValues: ["one_time", "subscription", "pilot", "revenue_share"],
      caseTransform: "lower",
    },
    {
      key: "visibility",
      label: "Visibility",
      placeholder: "private",
      help: "Who can see the listing preview once released.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["public", "partner", "private"],
      caseTransform: "lower",
    },
    {
      key: "previewGate",
      label: "Preview gate",
      placeholder: "nda_required",
      help: "Gate applied before a buyer can inspect sample records.",
      kind: "text",
      maxLength: 30,
      allowedValues: ["public", "nda_required", "operator_approved"],
      caseTransform: "lower",
    },
    {
      key: "samplePreviewUri",
      label: "Sample preview URI",
      placeholder: "s3://samples/receipts/preview.jsonl",
      help: "Watermarked sample preview object or bundle URI.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "refreshCadence",
      label: "Refresh cadence",
      placeholder: "monthly",
      help: "Buyer-facing listing refresh cadence.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "licenseTier",
      label: "License tier",
      placeholder: "evaluation",
      help: "Default listing license tier.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["standard", "evaluation", "enterprise", "exclusive"],
      caseTransform: "lower",
    },
  ],
  private_offer: [
    {
      key: "offerValueCents",
      label: "Offer value in cents",
      placeholder: "250000",
      help: "Private-offer value stored as integer minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "currency",
      label: "Currency",
      placeholder: "USD",
      help: "Supported offer currency.",
      kind: "text",
      maxLength: 3,
      allowedValues: ["USD", "EUR", "GBP"],
      caseTransform: "upper",
    },
    {
      key: "expiresAt",
      label: "Expiry date",
      placeholder: "2026-06-30",
      help: "Offer expiry date or deadline note.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "previewGate",
      label: "Preview gate",
      placeholder: "operator_approved",
      help: "Gate applied to the private-offer preview.",
      kind: "text",
      maxLength: 30,
      allowedValues: ["nda_required", "operator_approved"],
      caseTransform: "lower",
    },
    {
      key: "samplePreviewUri",
      label: "Sample preview URI",
      placeholder: "s3://samples/private-offers/acme-preview.jsonl",
      help: "Private-offer sample preview object or bundle URI.",
      kind: "text",
      maxLength: 240,
    },
  ],
  sample_preview_access: [
    {
      key: "watermarkSubject",
      label: "Watermark subject",
      placeholder: "buyer_org",
      help: "Watermark identity applied to the sample preview.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["buyer_org", "buyer_contact", "operator"],
      caseTransform: "lower",
    },
    {
      key: "expiresAt",
      label: "Expires at",
      placeholder: "2026-06-30",
      help: "Optional access-expiry timestamp or date.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "decisionReason",
      label: "Decision reason",
      placeholder: "NDA acknowledged and buyer scope matches listing.",
      help: "Operator decision rationale stored on the access record.",
      kind: "text",
      maxLength: 240,
    },
  ],
  run: [
    {
      key: "externalRunId",
      label: "External run ID",
      placeholder: "dagster/run/receipts-v4",
      help: "Dagster/Airflow/worker run identifier.",
      kind: "text",
      maxLength: 160,
    },
    {
      key: "retryCount",
      label: "Retry count",
      placeholder: "0",
      help: "Number of retry attempts recorded for this run.",
      kind: "integer",
      min: 0,
      max: 50,
    },
    {
      key: "startedAt",
      label: "Started at",
      placeholder: "2026-05-31T09:00:00Z",
      help: "Optional start timestamp.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "finishedAt",
      label: "Finished at",
      placeholder: "2026-05-31T10:15:00Z",
      help: "Optional finish timestamp.",
      kind: "text",
      maxLength: 40,
    },
  ],
  cost_entry: [
    {
      key: "buildId",
      label: "Build ID",
      placeholder: "bd_01J2BUILD",
      help: "Optional build to charge. Defaults to the latest active build.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "costBucket",
      label: "Cost bucket",
      placeholder: "compute",
      help: "Budget bucket used for sub-budget enforcement.",
      kind: "text",
      allowedValues: ["compute", "storage", "network", "llm", "external_api", "other"],
      caseTransform: "lower",
    },
    {
      key: "amountCents",
      label: "Amount in cents",
      placeholder: "12500",
      help: "Immutable cost amount stored in minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "metadataSummary",
      label: "Metadata summary",
      placeholder: "Reviewer batch cost estimate.",
      help: "Operator-readable cost metadata summary.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "overrideReason",
      label: "Override reason",
      placeholder: "Buyer approved extended LLM enrichment.",
      help: "Required when this entry exceeds the build budget or sub-budget.",
      kind: "text",
      maxLength: 240,
    },
  ],
  escalation_case: [
    {
      key: "escalationKind",
      label: "Escalation kind",
      placeholder: "supplier_delivery_failure",
      help: "Determines the default runbook and on-call route.",
      kind: "text",
      maxLength: 40,
      allowedValues: [
        "privacy_incident",
        "provenance_dispute",
        "supplier_delivery_failure",
        "buyer_dispute",
        "security_event",
        "platform_incident",
      ],
      caseTransform: "lower",
    },
    {
      key: "severity",
      label: "Severity",
      placeholder: "critical",
      help: "Operator-visible escalation severity.",
      kind: "text",
      maxLength: 20,
      allowedValues: ["info", "warning", "critical"],
      caseTransform: "lower",
    },
    {
      key: "sourceRecordType",
      label: "Source record type",
      placeholder: "delivery",
      help: "Optional source record type that triggered the escalation.",
      kind: "text",
      maxLength: 80,
      caseTransform: "lower",
    },
    {
      key: "sourceRecordId",
      label: "Source record ID",
      placeholder: "dl_01J2DELIVERY",
      help: "Optional source record identifier that triggered the escalation.",
      kind: "text",
      maxLength: 80,
    },
    {
      key: "runbookKey",
      label: "Runbook key",
      placeholder: "R-05",
      help: "Canonical R-01 to R-10 runbook. Blank values are auto-routed.",
      kind: "text",
      maxLength: 4,
      allowedValues: [
        "R-01",
        "R-02",
        "R-03",
        "R-04",
        "R-05",
        "R-06",
        "R-07",
        "R-08",
        "R-09",
        "R-10",
      ],
      caseTransform: "upper",
    },
    {
      key: "routedTo",
      label: "Routed to",
      placeholder: "supplier_operations",
      help: "On-call queue or team responsible for the runbook.",
      kind: "text",
      maxLength: 80,
      caseTransform: "lower",
    },
    {
      key: "slaDueAt",
      label: "SLA due at",
      placeholder: "2026-05-13T17:00:00Z",
      help: "Optional SLA timestamp. Blank values use the runbook SLA default.",
      kind: "text",
      maxLength: 40,
    },
    {
      key: "resolutionSummary",
      label: "Resolution summary",
      placeholder: "Supplier re-delivered the sample and buyer timeline was updated.",
      help: "Required before a case can be resolved.",
      kind: "text",
      maxLength: 240,
    },
  ],
  label_batch: [
    {
      key: "queueDepth",
      label: "Queue depth",
      placeholder: "120",
      help: "Active labeling tasks waiting for review or adjudication.",
      kind: "integer",
      min: 0,
    },
    {
      key: "agreementScore",
      label: "Agreement score",
      placeholder: "0.87",
      help: "Optional reviewer agreement score from 0 to 1.",
      kind: "decimal",
      min: 0,
      max: 1,
      step: "0.001",
    },
  ],
  active_learning_loop: [
    {
      key: "strategy",
      label: "Sampling strategy",
      placeholder: "hybrid_uncertainty_diversity",
      help: "FiftyOne Brain, Lightly-style embeddings, or the combined strategy.",
      kind: "text",
      maxLength: 40,
      allowedValues: [
        "fiftyone_brain",
        "lightly_embeddings",
        "hybrid_uncertainty_diversity",
      ],
      caseTransform: "lower",
    },
    {
      key: "candidateSourceUri",
      label: "Candidate source URI",
      placeholder: "s3://silver/candidates/crop-v1.jsonl",
      help: "Manifest of silver-layer candidate records eligible for sampling.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "embeddingIndexUri",
      label: "Embedding index URI",
      placeholder: "s3://indexes/crop-lightly-v1.lance",
      help: "FiftyOne Brain or Lightly-style embedding index used for diversity.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "modelSnapshotUri",
      label: "Model snapshot URI",
      placeholder: "s3://models/crop-assistant-v2",
      help: "Assistant model snapshot that produced uncertainty scores.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "uncertaintyMetric",
      label: "Uncertainty metric",
      placeholder: "entropy",
      help: "Model uncertainty metric used for reviewer routing.",
      kind: "text",
      maxLength: 80,
      caseTransform: "lower",
    },
    {
      key: "diversityMetric",
      label: "Diversity metric",
      placeholder: "embedding_distance",
      help: "Embedding diversity metric used to avoid redundant samples.",
      kind: "text",
      maxLength: 80,
      caseTransform: "lower",
    },
    {
      key: "boundaryMetric",
      label: "Boundary metric",
      placeholder: "margin",
      help: "Decision-boundary metric used to catch class edge cases.",
      kind: "text",
      maxLength: 80,
      caseTransform: "lower",
    },
    {
      key: "targetSampleSize",
      label: "Target sample size",
      placeholder: "128",
      help: "Number of active-learning items requested for this loop.",
      kind: "integer",
      min: 1,
    },
    {
      key: "selectedCount",
      label: "Selected count",
      placeholder: "96",
      help: "Number of candidates selected into the reviewer queue.",
      kind: "integer",
      min: 0,
    },
    {
      key: "selectionManifestUri",
      label: "Selection manifest URI",
      placeholder: "s3://manifests/active-learning/crop-loop-v1.json",
      help: "Reproducible manifest of selected item refs and scores.",
      kind: "text",
      maxLength: 240,
    },
    {
      key: "reviewerRouting",
      label: "Reviewer routing",
      placeholder: "cv_specialists:priority_high",
      help: "Reviewer cohort or routing policy for selected active-learning items.",
      kind: "text",
      maxLength: 160,
    },
  ],
  quote: [
    {
      key: "amountCents",
      label: "Amount in cents",
      placeholder: "250000",
      help: "Quote amount stored as integer minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "currency",
      label: "Currency",
      placeholder: "USD",
      help: "Supported billing currency for this quote.",
      kind: "text",
      maxLength: 3,
      allowedValues: ["USD", "EUR", "GBP"],
      caseTransform: "upper",
    },
  ],
  invoice: [
    {
      key: "amountCents",
      label: "Amount in cents",
      placeholder: "250000",
      help: "Invoice amount stored as integer minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "currency",
      label: "Currency",
      placeholder: "USD",
      help: "Supported invoice currency.",
      kind: "text",
      maxLength: 3,
      allowedValues: ["USD", "EUR", "GBP"],
      caseTransform: "upper",
    },
  ],
  payout: [
    {
      key: "amountCents",
      label: "Amount in cents",
      placeholder: "125000",
      help: "Supplier payout amount stored as integer minor units.",
      kind: "integer",
      min: 0,
    },
    {
      key: "currency",
      label: "Currency",
      placeholder: "USD",
      help: "Supported payout currency.",
      kind: "text",
      maxLength: 3,
      allowedValues: ["USD", "EUR", "GBP"],
      caseTransform: "upper",
    },
  ],
} as const satisfies Partial<
  Record<OperatorRecordCrudType, readonly OperatorRecordFieldDescriptor[]>
>;

export function isOperatorRecordCrudType(
  value: string
): value is OperatorRecordCrudType {
  return operatorRecordCrudTypes.includes(value as OperatorRecordCrudType);
}

export function getOperatorRecordCrudDescriptor(
  recordType: string
): OperatorRecordCrudDescriptor | null {
  return isOperatorRecordCrudType(recordType)
    ? operatorRecordCrudDescriptors[recordType]
    : null;
}

export function getOperatorRecordFormGuidance(
  recordType: string
): OperatorRecordFormGuidance | null {
  return isOperatorRecordCrudType(recordType)
    ? operatorRecordFormGuidance[recordType]
    : null;
}

export function getOperatorRecordFieldDescriptors(
  recordType: string
): readonly OperatorRecordFieldDescriptor[] {
  if (!isOperatorRecordCrudType(recordType)) {
    return [];
  }

  const descriptors =
    operatorRecordFieldDescriptors as Partial<
      Record<OperatorRecordCrudType, readonly OperatorRecordFieldDescriptor[]>
    >;

  return descriptors[recordType] ?? [];
}
