import {
  Briefcase,
  Calculator,
  CalendarCheck,
  ClipboardCheck,
  Cog,
  FileSearch,
  Handshake,
  Headset,
  HeartPulse,
  Landmark,
  Plane,
  Receipt,
  Router,
  Scale,
  ShieldCheck,
  Stethoscope,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ExpertRoleIcon } from "@/lib/sectors/content";

/** The tool of each trade, for the expert roles named in `content/sectors`. */
export const EXPERT_ROLE_ICONS: Record<ExpertRoleIcon, LucideIcon> = {
  adjuster: FileSearch,
  claims: ClipboardCheck,
  calculator: Calculator,
  handshake: Handshake,
  wrench: Wrench,
  cog: Cog,
  stethoscope: Stethoscope,
  heart: HeartPulse,
  calendar: CalendarCheck,
  bank: Landmark,
  shield: ShieldCheck,
  zap: Zap,
  receipt: Receipt,
  headset: Headset,
  router: Router,
  scale: Scale,
  briefcase: Briefcase,
  plane: Plane,
};
